### Create a new user
POST http://localhost:3000/auth/signup
content-type: application/json

{
  "email": "simen@dehlin.dev",
  "password": "12345678"
}


### Find a user with particular ID
GET http://localhost:3000/auth/1